services:
  - type: web
    name: excalidraw
    image: kiliandeca/excalidraw
    ports:
      - 80:80
    environment:
      - BACKEND_V2_GET_URL=http://localhost:8080/api/v2/scenes/
      - BACKEND_V2_POST_URL=http://localhost:8080/api/v2/scenes/
      - LIBRARY_URL=https://libraries.excalidraw.com
      - LIBRARY_BACKEND=https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries
      - SOCKET_SERVER_URL=http://localhost:5000/
      - STORAGE_BACKEND=http
      - HTTP_STORAGE_BACKEND_URL=http://localhost:8080/api/v2

  - type: web
    name: excalidraw-storage-backend
    image: kiliandeca/excalidraw-storage-backend
    ports:
      - 8080:8080
    environment:
      - STORAGE_URI=redis://redis:6379

  - type: web
    name: excalidraw-room
    image: excalidraw/excalidraw-room
    ports:
      - 5000:80

  - type: web
    name: redis
    image: redis
    ports:
      - 6379:6379
